services:
  laravel-dev:
    container_name: laravel-dev
    image: zydhanlinnar11/laravel-dev:main
    volumes:
      - ./src:/var/www/html
    dns:
      - 1.1.1.1
      - 1.0.0.1
    env_file: .env.dev
    networks:
      - nginx-proxy-network
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  nginx-proxy-network:
    external: true
