FROM php:8.2.3-fpm-alpine3.17

LABEL mantainer="zydhanlinnar11@gmail.com"
LABEL description="PHP alpine - docker container with dependencies and gRPC extension"

# Install composer
COPY --from=composer:2.5.4 /usr/bin/composer /usr/bin/composer

# Change timezone
RUN echo "Asia/Jakarta" > /etc/timezone \
    && apk add --no-cache supervisor nginx \
    && mkdir -p /etc/supervisor.d/ \
    && mkdir -p /var/log/supervisord/ \
    && mkdir -p /etc/nginx \
    && docker-php-ext-install bcmath \
    && apk add --no-cache linux-headers $PHPIZE_DEPS \
    && pecl install xdebug-3.2.0 \
    && docker-php-ext-enable xdebug \
    && apk del --purge --no-cache $PHPIZE_DEPS \
    && apk update \
    && apk add --no-cache autoconf zlib-dev g++ gcc linux-headers make zlib grpc \
    && pecl install grpc-1.49.0 protobuf \
    && apk del --purge --no-cache $PHPIZE_DEPS autoconf zlib-dev g++ gcc linux-headers make zlib \
    && echo "extension=protobuf.so" > /usr/local/etc/php/conf.d/docker-php-ext-protobuf.ini \
    && echo "extension=grpc.so" > /usr/local/etc/php/conf.d/docker-php-ext-grpc.ini \
    && apk add --no-cache freetype-dev libpng-dev jpeg-dev libjpeg-turbo-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd

# Copy configurations
COPY config/supervisord.ini /etc/supervisor.d/supervisord.ini
COPY config/laravel.conf /etc/nginx/http.d/default.conf
COPY config/php-jakarta-timezone.ini /usr/local/etc/php/conf.d/php-jakarta-timezone.ini
COPY config/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
COPY config/error_reporting.ini /usr/local/etc/php/conf.d/error_reporting.ini

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor.d/supervisord.ini"]
