services:
  laravel-docker-image:
    container_name: laravel-docker-image
    image: zydhanlinnar11/laravel-docker-image:main
    volumes:
      - ./src:/var/www/html
    dns:
      - 1.1.1.1
      - 1.0.0.1
    env_file: .env
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
