services:
  laravel-prod:
    container_name: laravel-prod
    image: zydhanlinnar11/laravel-prod:latest
    volumes:
      - ./src:/var/www/html
    env_file: .env.prod
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
