FROM php:8.2.2-fpm-alpine3.17

# Install composer
COPY --from=composer:2.5.3 /usr/bin/composer /usr/bin/composer

# Change timezone
RUN echo "Asia/Jakarta" > /etc/timezone \
    && docker-php-ext-install bcmath \
    && apk add --no-cache linux-headers $PHPIZE_DEPS \
    && pecl install xdebug-3.2.0 \
    && docker-php-ext-enable xdebug \
    && apk del --purge --no-cache $PHPIZE_DEPS

# Copy configurations
COPY config/php-jakarta-timezone.ini /usr/local/etc/php/conf.d/php-jakarta-timezone.ini
COPY config/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
COPY config/error_reporting.ini /usr/local/etc/php/conf.d/error_reporting.ini

CMD ["php", "artisan", "serve", "--port=80", "--host=0.0.0.0"]
