services:
  laravel-docker-image-prod:
    container_name: laravel-docker-image-prod
    image: zydhanlinnar11/laravel-docker-image-prod:latest
    volumes:
      - ./src:/var/www/html
    env_file: .env.prod
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
