version: '3.8'
services:
    laravel-docker-image:
        container_name: laravel-docker-image
        image: zydhanlinnar11/laravel-docker-image
        volumes:
            - ./src:/var/www/html
        env_file: .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - nginx-proxy-network
        ports:
            - "8080:80"

networks:
    nginx-proxy-network:
        external: true